### ISSUE TITLE
createStatementではなくpreparedStatementを使用すべき

### ISSUE THREAD

**Issue by siloneco** [AzisabaNetwork/KDStatusReloaded#6]
createStatementでの変数挿入は危険なためpreparedStatementを使用すべき  

修正すべきクラス:
* [KillDeathDataContainer.java](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/KillDeathDataContainer.java)
* [PlayerDataMySQLController.java](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/PlayerDataMySQLController.java)
* [PlayerDataSQLController.java](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/PlayerDataSQLController.java)

**Comment by siloneco** [comment]
漏れがあるかもしれないので他の人も修正すべきファイルが他にないか確認よろしく

**Comment by matsu1213** [comment]
createStatementってどこで使われてます...？(よく理解できてない)

**Comment by siloneco** [comment]
あ、ごめんpreparedStatementは使われてるのか。ただ変数の代入方法が間違っているな  
例えば[KillDeathDataContainer.java#L228](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/KillDeathDataContainer.java#L228)みたいな、変数を直接文字列にくっつける行為はSQLインジェクションを可能にしてしまう

[SQLHandler.java#L71](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/SQLHandler.java#L71)とかのメソッドに直接代入する値を渡して、preparedStatementメソッドの第二引数以降にそれを入れるようにメソッドを改造しないといけない

**Comment by siloneco** [comment]
e24451c で修正された模様

**Comment by matsu1213** [comment]
SQLiteの方もやります？

**Comment by siloneco** [comment]
もう使用してないなら、クラスごと削除してしまっても問題ないので、修正いらない  
できれば間違えて使用しないように [KDStatusReloaded.java](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/KDStatusReloaded.java) から要らないグローバル変数を消して、v1.3.1として更新してほしい

**Comment by matsu1213** [comment]
https://github.com/AzisabaNetwork/KDStatusReloaded/commit/a270b812342a739a7a7a0464d4ec5ea00243b501

移行完了後に不要なクラスや変数を削除します
