### ISSUE TITLE
SQLiteからMySQLへ移行する際のAPI対応

### ISSUE THREAD

**Issue by siloneco** [AzisabaNetwork/KDStatusReloaded#7]
[KillDeathDataContainer.java](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/KillDeathDataContainer.java) は他プラグインから `((KDStatusReloaded) Bukkit.getPluginManager().getPlugin("KDStatusReloaded")).getKdDataContainer()` のように取得され、APIインターフェースとして使用されているので、メソッドの名前や引数等を改変することなくMySQLに対応しなければならない

## 使用例
* [RankingDisplayer/DisplayListener.java#L302](https://github.com/AzisabaNetwork/RankingDisplayer/blob/master/src/main/java/jp/azisaba/lgw/rankingdisplayer/DisplayListener.java#L302)
* [LeonGunWar/KDTeamDistributor.java#L50](https://github.com/AzisabaNetwork/LeonGunWar/blob/master/src/main/java/net/azisaba/lgw/core/distributors/KDTeamDistributor.java#L50)

**Comment by matsu1213** [comment]
MySQLへ移行済みかどうかは変数で管理しているので、メゾットの名前や引数等に変更はないはず...です

**Comment by siloneco** [comment]
ここ ( [KillDeathDataContainer.java#L228](https://github.com/AzisabaNetwork/KDStatusReloaded/blob/master/src/main/java/jp/azisaba/lgw/kdstatus/sql/KillDeathDataContainer.java#L228) ) とか、SQLiteの方使ってない？

**Comment by siloneco** [comment]
あぁ、ごめん、最初にif (isMigrated) があるのか、ならヨシ！

**Comment by siloneco** [comment]
インデントがされてないから見落としていた…

**Comment by matsu1213** [comment]
ごめんなさい...
